name: CI/CD

on:
    push:
        branches:
            - master
            - alpha
            - beta
    pull_request:
        branches:
            - master
            - alpha
            - beta

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: npm install

            - run: npm run test

    release:
        runs-on: ubuntu-latest
        needs:
            - test
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: npm install

            - name: Release 🚀
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
